// app/frontend/src/views/CartView.vue
<template>
  <div class="cart-root">
    <PosterStrip left="LA BOLSA · CONFIRMAR PEDIDO" :right="`${cart.count} ÍTEMS`" />

    <nav class="cart-nav hairline-b">
      <RouterLink to="/" class="back eyebrow">← CATÁLOGO</RouterLink>
      <BLogo :size="20" />
      <ThemeToggle />
    </nav>

    <div v-if="!cart.items.length" class="empty-state">
      <p class="f-display" style="font-size:32px">Tu bolsa está <em class="accent">vacía.</em></p>
      <RouterLink to="/" class="btn btn-primary" style="margin-top:24px;height:48px;width:220px">
        VER CATÁLOGO →
      </RouterLink>
    </div>

    <div v-else class="cart-grid">

      <!-- Items -->
      <div class="items-col">
        <h2 class="f-display" style="font-size:36px;margin-bottom:24px">
          Tu <em class="accent">bolsa.</em>
        </h2>

        <div v-for="item in cart.items" :key="item.id" class="item dashed-b">
          <AlbumCover :album="itemAlbum(item)" :size="72" />
          <div class="item-info">
            <p class="f-display" style="font-size:16px;line-height:1.1">{{ item.titulo_album }}</p>
            <p class="eyebrow" style="margin-top:4px">{{ item.artista }}</p>
            <FormatChip :formato="item.tipo_formato || 'Vinilo'" style="margin-top:6px" />
          </div>
          <div class="item-right">
            <p class="f-display brass" style="font-size:18px">
              Q {{ (Number(item.precio) * item.cantidad).toLocaleString('es-GT') }}
            </p>
            <div class="qty-ctrl">
              <button @click="cart.updateQty(item.id, item.cantidad - 1)">−</button>
              <span class="eyebrow">{{ item.cantidad }}</span>
              <button @click="cart.updateQty(item.id, item.cantidad + 1)">+</button>
            </div>
            <button class="remove-btn eyebrow" @click="cart.remove(item.id)">QUITAR</button>
          </div>
        </div>
      </div>

      <!-- Checkout -->
      <div class="checkout-col hairline">
        <div class="checkout-header hairline-b">
          <p class="eyebrow brass">DATOS DE PEDIDO</p>
        </div>
        <div class="checkout-body">

          <div v-if="perfil" class="perfil-info">
            <p class="eyebrow">CLIENTE</p>
            <p class="f-display" style="font-size:16px;margin-top:4px">{{ perfil.nombre }}</p>
            <p class="eyebrow" style="color:var(--mute);margin-top:2px">{{ perfil.correo }}</p>
          </div>

          <!-- Recoger en tienda -->
          <label class="option-row">
            <input type="checkbox" v-model="recogerEnTienda" class="checkbox" />
            <span class="eyebrow">RECOGER EN TIENDA (SIN ENVÍO)</span>
          </label>

          <template v-if="!recogerEnTienda">
            <!-- Fuente de datos: guardados vs manual -->
            <div class="datos-source">
              <p class="eyebrow" style="color:var(--mute);font-size:10px;margin-bottom:8px">DATOS DE FACTURACIÓN Y ENTREGA</p>
              <label class="option-row" style="padding:10px 12px;border:1px solid var(--line);margin-bottom:6px" :style="datosSource==='saved' ? 'border-color:var(--brass)' : ''">
                <input type="radio" v-model="datosSource" value="saved" class="checkbox" />
                <div>
                  <span class="eyebrow" style="color:var(--ink)">USAR DATOS GUARDADOS</span>
                  <span class="eyebrow" style="display:block;color:var(--mute);font-size:9px;margin-top:3px">
                    NIT: {{ perfil?.NIT || 'CF' }} · {{ perfil?.direccion || 'Sin dirección registrada' }}
                  </span>
                </div>
              </label>
              <label class="option-row" style="padding:10px 12px;border:1px solid var(--line)" :style="datosSource==='custom' ? 'border-color:var(--brass)' : ''">
                <input type="radio" v-model="datosSource" value="custom" class="checkbox" />
                <span class="eyebrow" style="color:var(--ink)">INGRESAR DATOS PARA ESTA COMPRA</span>
              </label>
            </div>

            <template v-if="datosSource === 'custom'">
              <div class="field">
                <label>NIT de facturación</label>
                <input v-model="nit" :placeholder="perfil?.NIT || 'CF'" />
              </div>
              <div class="field">
                <label>Dirección de entrega <span style="color:var(--mute)">(opcional)</span></label>
                <input v-model="direccion" :placeholder="perfil?.direccion || 'Sin dirección'" />
              </div>
              <label class="option-row" style="margin-top:0">
                <input type="checkbox" v-model="actualizarPerfil" class="checkbox" />
                <span class="eyebrow">GUARDAR COMO NUEVOS PREDETERMINADOS</span>
              </label>
            </template>
          </template>

          <div class="total-box hairline-t">
            <div class="total-row">
              <span class="eyebrow">SUBTOTAL</span>
              <span class="f-display" style="font-size:14px">Q {{ cart.total }}</span>
            </div>
            <div class="total-row">
              <span class="eyebrow">ENVÍO</span>
              <span class="eyebrow" style="color:var(--brass)">{{ recogerEnTienda ? 'GRATIS' : 'A COORDINAR' }}</span>
            </div>
            <div class="total-row total-final">
              <span class="eyebrow">TOTAL</span>
              <span class="f-display brass" style="font-size:28px">Q {{ cart.total }}</span>
            </div>
          </div>

          <p v-if="errorMsg" class="eyebrow" style="color:var(--velvet);font-size:10px">{{ errorMsg }}</p>

          <button class="btn btn-primary" style="width:100%;height:52px" @click="showConfirm = true" :disabled="loading || !cart.items.length">
            REVISAR Y CONFIRMAR →
          </button>
        </div>
      </div>

    </div>

    <!-- Modal: confirmar antes de comprar -->
    <Transition name="fade">
      <div v-if="showConfirm" class="confirm-overlay" @click.self="showConfirm = false">
        <div class="confirm-card hairline">
          <p class="eyebrow velvet" style="font-size:10px">● CONFIRMAR PEDIDO</p>
          <h2 class="f-display" style="font-size:28px;margin-top:10px">¿Todo correcto?</h2>

          <!-- Items -->
          <div class="confirm-items" style="margin-top:16px">
            <div v-for="item in cart.items" :key="item.id" class="eyebrow confirm-item">
              {{ item.titulo_album }} ({{ item.tipo_formato }}) × {{ item.cantidad }} —
              <span class="brass">Q {{ (Number(item.precio) * item.cantidad).toLocaleString('es-GT') }}</span>
            </div>
          </div>

          <!-- Datos de entrega -->
          <div style="margin-top:16px;border-top:1px solid var(--line);padding-top:14px;display:flex;flex-direction:column;gap:6px">
            <div class="eyebrow confirm-item">
              <span>CLIENTE</span>
              <span style="color:var(--ink)">{{ perfil?.nombre }}</span>
            </div>
            <div class="eyebrow confirm-item" v-if="!recogerEnTienda">
              <span>NIT</span>
              <span style="color:var(--ink)">{{ datosSource === 'saved' ? (perfil?.NIT || 'CF') : (nit || 'CF') }}</span>
            </div>
            <div class="eyebrow confirm-item" v-if="!recogerEnTienda && (datosSource === 'saved' ? perfil?.direccion : direccion)">
              <span>DIRECCIÓN</span>
              <span style="color:var(--ink)">{{ datosSource === 'saved' ? perfil?.direccion : direccion }}</span>
            </div>
            <div class="eyebrow confirm-item">
              <span>ENVÍO</span>
              <span style="color:var(--brass)">{{ recogerEnTienda ? 'RECOGER EN TIENDA' : 'A COORDINAR' }}</span>
            </div>
          </div>

          <p class="f-display brass" style="font-size:28px;text-align:right;margin-top:16px">
            Total: Q {{ cart.total }}
          </p>

          <p v-if="errorMsg" class="eyebrow" style="color:var(--velvet);font-size:10px;margin-top:8px">{{ errorMsg }}</p>

          <div style="display:flex;gap:10px;margin-top:20px">
            <button class="btn btn-outline" style="flex:1;height:44px" @click="showConfirm = false">CANCELAR</button>
            <button class="btn btn-primary" style="flex:1;height:44px" @click="checkout" :disabled="loading">
              {{ loading ? 'PROCESANDO…' : 'CONFIRMAR →' }}
            </button>
          </div>
        </div>
      </div>
    </Transition>

    <!-- Confirmación -->
    <Transition name="fade">
      <div v-if="confirmacion" class="confirm-overlay">
        <div class="confirm-card hairline">
          <p class="eyebrow velvet" style="font-size:10px">● PEDIDO CONFIRMADO</p>
          <h2 class="f-display" style="font-size:36px;margin-top:12px">
            ¡Listo, <em class="accent">{{ auth.user?.nombre?.split(' ')[0] }}!</em>
          </h2>
          <p class="f-serif" style="font-size:18px;color:var(--mute);margin-top:8px">
            Tu pedido #{{ confirmacion.id_compra }} ha sido registrado.
          </p>
          <div class="confirm-items">
            <div v-for="item in confirmacion.items" :key="item.id_producto" class="eyebrow confirm-item">
              {{ item.nombre_producto }} × {{ item.cantidad }} —
              Q {{ Number(item.subtotal).toLocaleString('es-GT') }}
            </div>
          </div>
          <p class="f-display brass" style="font-size:24px;margin-top:16px">
            Total: Q {{ confirmacion.total }}
          </p>
          <div style="display:flex;gap:12px;margin-top:24px">
            <RouterLink to="/perfil" class="btn btn-outline" style="height:44px;flex:1">VER MIS PEDIDOS</RouterLink>
            <RouterLink to="/" class="btn btn-primary" style="height:44px;flex:1">SEGUIR COMPRANDO</RouterLink>
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useAuthStore }  from '@/stores/auth.js'
import { useCartStore }  from '@/stores/cart.js'
import api from '@/api/index.js'
import PosterStrip from '@/components/PosterStrip.vue'
import BLogo       from '@/components/BLogo.vue'
import ThemeToggle from '@/components/ThemeToggle.vue'
import AlbumCover  from '@/components/AlbumCover.vue'
import FormatChip  from '@/components/FormatChip.vue'

const auth    = useAuthStore()
const cart    = useCartStore()
const perfil  = ref(null)
const loading = ref(false)
const errorMsg = ref('')
const confirmacion = ref(null)

const recogerEnTienda  = ref(false)
const actualizarPerfil = ref(false)
const datosSource      = ref('saved')   // 'saved' | 'custom'
const showConfirm      = ref(false)
const nit      = ref('')
const direccion = ref('')

function itemAlbum(item) {
  return { titulo: item.titulo_album, artista: item.artista, url_portada: item.url_portada }
}

onMounted(async () => {
  if (auth.user?.rol === 'cliente') {
    try {
      const { data } = await api.get('/clientes/mi-perfil')
      perfil.value = data
      nit.value      = data.NIT      || 'CF'
      direccion.value = data.direccion || ''
    } catch { /* no perfil */ }
  }
})

async function checkout() {
  errorMsg.value = ''; loading.value = true
  try {
    // Si eligió datos manuales y quiere guardarlos como predeterminados
    if (datosSource.value === 'custom' && actualizarPerfil.value && !recogerEnTienda.value) {
      await api.patch('/clientes/mi-perfil', {
        NIT:       nit.value      || undefined,
        direccion: direccion.value || null
      })
    }

    const items = cart.items.map(i => ({ id_producto: i.id, cantidad: i.cantidad }))
    const { data } = await api.post('/ventas', { items })

    showConfirm.value  = false
    confirmacion.value = data
    cart.clear()
  } catch (e) {
    errorMsg.value = e.response?.data?.error || 'Error al procesar el pedido'
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.cart-root { display:flex; flex-direction:column; height:100vh; overflow:hidden; background:var(--bg); }

.cart-nav {
  display:flex; align-items:center; justify-content:space-between;
  height:58px; padding:0 24px; background:var(--paper); flex-shrink:0;
}
.back { font-size:10px; letter-spacing:.22em; color:var(--mute); text-decoration:none; }
.back:hover { color:var(--ink); }

.empty-state { flex:1; display:flex; flex-direction:column; align-items:center; justify-content:center; }

.cart-grid {
  display:grid; grid-template-columns:1fr 380px;
  flex:1; overflow:hidden;
}

.items-col { overflow-y:auto; padding:28px 32px; }

.item {
  display:flex; align-items:center; gap:16px;
  padding:16px 0;
}
.item-info { flex:1; display:flex; flex-direction:column; }
.item-right { display:flex; flex-direction:column; align-items:flex-end; gap:8px; }
.qty-ctrl { display:flex; align-items:center; gap:10px; border:1px solid var(--line); padding:3px 10px; }
.qty-ctrl button { color:var(--mute); background:none; border:none; font-size:14px; cursor:pointer; }
.remove-btn { color:var(--mute); background:none; border:none; cursor:pointer; font-size:9px; }
.remove-btn:hover { color:var(--velvet); }

.checkout-col { display:flex; flex-direction:column; overflow-y:auto; background:var(--paper); }
.checkout-header { padding:20px 24px; }
.checkout-body { padding:20px 24px; display:flex; flex-direction:column; gap:18px; }

.perfil-info { padding-bottom:14px; border-bottom:1px dashed var(--line); }

.option-row {
  display:flex; align-items:center; gap:10px; cursor:pointer;
  padding:8px 0;
}
.checkbox { width:14px; height:14px; cursor:pointer; accent-color:var(--velvet); }

.field-hint { font-size:8px; letter-spacing:.18em; color:var(--mute); margin-top:2px; display:block; }
.datos-source { display:flex; flex-direction:column; }
.confirm-item { display:flex; justify-content:space-between; gap:12px; color:var(--mute); font-size:10px; padding:3px 0; }

.total-box { display:flex; flex-direction:column; gap:10px; padding-top:14px; }
.total-row { display:flex; justify-content:space-between; align-items:center; }
.total-final { padding-top:10px; border-top:1px solid var(--line); }

.confirm-overlay {
  position:fixed; inset:0; background:rgba(0,0,0,.7); z-index:200;
  display:flex; align-items:center; justify-content:center; padding:24px;
}
.confirm-card {
  background:var(--paper); padding:36px; max-width:500px; width:100%;
  display:flex; flex-direction:column;
}
.confirm-items { display:flex; flex-direction:column; gap:6px; margin-top:16px; }
.confirm-item { color:var(--mute); font-size:10px; }

.fade-enter-active, .fade-leave-active { transition:opacity 200ms; }
.fade-enter-from, .fade-leave-to { opacity:0; }
</style>

// app/frontend/src/views/CartView.jsx
import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../AuthContext';
import { useCart } from '../CartContext';
import api from '../api';
import { PosterStrip } from '../components/PosterStrip';
import { BLogo } from '../components/BLogo';
import { ThemeToggle } from '../components/ThemeToggle';
import { AlbumCover } from '../components/AlbumCover';
import { FormatChip } from '../components/FormatChip';
import './CartView.css';

export default function CartView() {
  const auth = useAuth();
  const cart = useCart();
  const [perfil, setPerfil] = useState(null);
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [confirmacion, setConfirmacion] = useState(null);

  const [recogerEnTienda, setRecogerEnTienda] = useState(false);
  const [actualizarPerfil, setActualizarPerfil] = useState(false);
  const [datosSource, setDatosSource] = useState('saved');
  const [showConfirm, setShowConfirm] = useState(false);
  const [nit, setNit] = useState('');
  const [direccion, setDireccion] = useState('');

  useEffect(() => {
    if (auth.user?.rol === 'cliente') {
      api.get('/clientes/mi-perfil').then(({ data }) => {
        setPerfil(data);
        setNit(data.NIT || '');
        setDireccion(data.direccion || '');
      }).catch(() => {});
    }
  }, [auth.user]);

  const checkout = async () => {
    setErrorMsg(''); setLoading(true);
    try {
      if (datosSource === 'custom' && actualizarPerfil && !recogerEnTienda) {
        await api.patch('/clientes/mi-perfil', { NIT: nit || undefined, direccion: direccion || null });
      }
      const items = cart.items.map(i => ({ id_producto: i.id, cantidad: i.cantidad }));
      const { data } = await api.post('/ventas', { items });
      setShowConfirm(false);
      setConfirmacion(data);
      cart.clear();
    } catch (e) {
      setErrorMsg(e.response?.data?.error || 'Error al procesar el pedido');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="cart-root">
      <PosterStrip left="LA BOLSA · CONFIRMAR PEDIDO" right={`${cart.count} ÍTEMS`} />

      <nav className="cart-nav hairline-b">
        <Link to="/" className="back eyebrow">← CATÁLOGO</Link>
        <BLogo size={20} />
        <ThemeToggle />
      </nav>

      {!cart.items.length && !confirmacion ? (
        <div className="empty-state">
          <p className="f-display" style={{ fontSize: '32px' }}>Tu bolsa está <em className="accent">vacía.</em></p>
          <Link to="/" className="btn btn-primary" style={{ marginTop: '24px', height: '48px', width: '220px' }}>
            VER CATÁLOGO →
          </Link>
        </div>
      ) : !confirmacion ? (
        <div className="cart-grid">
          <div className="items-col">
            <h2 className="f-display" style={{ fontSize: '36px', marginBottom: '24px' }}>Tu <em className="accent">bolsa.</em></h2>
            {cart.items.map(item => (
              <div key={item.id} className="item dashed-b">
                <AlbumCover album={{ titulo: item.titulo_album, artista: item.artista, url_portada: item.url_portada }} size={72} />
                <div className="item-info">
                  <p className="f-display" style={{ fontSize: '16px', lineHeight: 1.1 }}>{item.titulo_album}</p>
                  <p className="eyebrow" style={{ marginTop: '4px' }}>{item.artista}</p>
                  <FormatChip formato={item.tipo_formato || 'Vinilo'} style={{ marginTop: '6px' }} />
                </div>
                <div className="item-right">
                  <p className="f-display brass" style={{ fontSize: '18px' }}>Q {(Number(item.precio) * item.cantidad).toLocaleString('es-GT')}</p>
                  <div className="qty-ctrl">
                    <button onClick={() => cart.updateQty(item.id, item.cantidad - 1)}>−</button>
                    <span className="eyebrow">{item.cantidad}</span>
                    <button onClick={() => cart.updateQty(item.id, item.cantidad + 1)}>+</button>
                  </div>
                  <button className="remove-btn eyebrow" onClick={() => cart.remove(item.id)}>QUITAR</button>
                </div>
              </div>
            ))}
          </div>

          <div className="checkout-col hairline">
            <div className="checkout-header hairline-b"><p className="eyebrow brass">DATOS DE PEDIDO</p></div>
            <div className="checkout-body">
              {perfil && (
                <div className="perfil-info">
                  <p className="eyebrow">CLIENTE</p>
                  <p className="f-display" style={{ fontSize: '16px', marginTop: '4px' }}>{perfil.nombre}</p>
                  <p className="eyebrow" style={{ color: 'var(--mute)', marginTop: '2px' }}>{perfil.correo}</p>
                </div>
              )}

              <label className="option-row">
                <input type="checkbox" checked={recogerEnTienda} onChange={e => setRecogerEnTienda(e.target.checked)} className="checkbox" />
                <span className="eyebrow">RECOGER EN TIENDA (SIN ENVÍO)</span>
              </label>

              {!recogerEnTienda && (
                <>
                  <div className="datos-source">
                    <p className="eyebrow" style={{ color: 'var(--mute)', fontSize: '10px', marginBottom: '8px' }}>DATOS DE FACTURACIÓN Y ENTREGA</p>
                    <label className="option-row" style={{ padding: '10px 12px', border: `1px solid ${datosSource === 'saved' ? 'var(--brass)' : 'var(--line)'}`, marginBottom: '6px' }}>
                      <input type="radio" checked={datosSource === 'saved'} onChange={() => setDatosSource('saved')} className="checkbox" />
                      <div>
                        <span className="eyebrow" style={{ color: 'var(--ink)' }}>USAR DATOS GUARDADOS</span>
                        <span className="eyebrow" style={{ display: 'block', color: 'var(--mute)', fontSize: '9px', marginTop: '3px' }}>
                          NIT: {perfil?.NIT || 'CF'} · {perfil?.direccion || 'Sin dirección registrada'}
                        </span>
                      </div>
                    </label>
                    <label className="option-row" style={{ padding: '10px 12px', border: `1px solid ${datosSource === 'custom' ? 'var(--brass)' : 'var(--line)'}` }}>
                      <input type="radio" checked={datosSource === 'custom'} onChange={() => setDatosSource('custom')} className="checkbox" />
                      <span className="eyebrow" style={{ color: 'var(--ink)' }}>INGRESAR DATOS PARA ESTA COMPRA</span>
                    </label>
                  </div>

                  {datosSource === 'custom' && (
                    <>
                      <div className="field">
                        <label>NIT de facturación</label>
                        <input value={nit} onChange={e => setNit(e.target.value)} placeholder={perfil?.NIT || 'CF'} />
                      </div>
                      <div className="field">
                        <label>Dirección de entrega <span style={{ color: 'var(--mute)' }}>(opcional)</span></label>
                        <input value={direccion} onChange={e => setDireccion(e.target.value)} placeholder={perfil?.direccion || 'Sin dirección'} />
                      </div>
                      <label className="option-row" style={{ marginTop: 0 }}>
                        <input type="checkbox" checked={actualizarPerfil} onChange={e => setActualizarPerfil(e.target.checked)} className="checkbox" />
                        <span className="eyebrow">GUARDAR COMO NUEVOS PREDETERMINADOS</span>
                      </label>
                    </>
                  )}
                </>
              )}

              <div className="total-box hairline-t">
                <div className="total-row">
                  <span className="eyebrow">SUBTOTAL</span>
                  <span className="f-display" style={{ fontSize: '14px' }}>Q {cart.total}</span>
                </div>
                <div className="total-row">
                  <span className="eyebrow">ENVÍO</span>
                  <span className="eyebrow" style={{ color: 'var(--brass)' }}>{recogerEnTienda ? 'GRATIS' : 'A COORDINAR'}</span>
                </div>
                <div className="total-row total-final">
                  <span className="eyebrow">TOTAL</span>
                  <span className="f-display brass" style={{ fontSize: '28px' }}>Q {cart.total}</span>
                </div>
              </div>

              {errorMsg && <p className="eyebrow" style={{ color: 'var(--velvet)', fontSize: '10px' }}>{errorMsg}</p>}

              <button className="btn btn-primary" style={{ width: '100%', height: '52px' }} onClick={() => setShowConfirm(true)} disabled={loading || !cart.items.length}>
                REVISAR Y CONFIRMAR →
              </button>
            </div>
          </div>
        </div>
      ) : null}

      {showConfirm && (
        <div className="confirm-overlay" onClick={(e) => { if (e.target === e.currentTarget) setShowConfirm(false); }}>
          <div className="confirm-card hairline">
            <p className="eyebrow velvet" style={{ fontSize: '10px' }}>● CONFIRMAR PEDIDO</p>
            <h2 className="f-display" style={{ fontSize: '28px', marginTop: '10px' }}>¿Todo correcto?</h2>
            
            <div className="confirm-items" style={{ marginTop: '16px' }}>
              {cart.items.map(item => (
                <div key={item.id} className="eyebrow confirm-item">
                  {item.titulo_album} ({item.tipo_formato}) × {item.cantidad} — <span className="brass">Q {(Number(item.precio) * item.cantidad).toLocaleString('es-GT')}</span>
                </div>
              ))}
            </div>

            <div style={{ marginTop: '16px', borderTop: '1px solid var(--line)', paddingTop: '14px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
              <div className="eyebrow confirm-item"><span>CLIENTE</span><span style={{ color: 'var(--ink)' }}>{perfil?.nombre}</span></div>
              {!recogerEnTienda && <div className="eyebrow confirm-item"><span>NIT</span><span style={{ color: 'var(--ink)' }}>{datosSource === 'saved' ? (perfil?.NIT || 'CF') : (nit || 'CF')}</span></div>}
              {!recogerEnTienda && (datosSource === 'saved' ? perfil?.direccion : direccion) && <div className="eyebrow confirm-item"><span>DIRECCIÓN</span><span style={{ color: 'var(--ink)' }}>{datosSource === 'saved' ? perfil?.direccion : direccion}</span></div>}
              <div className="eyebrow confirm-item"><span>ENVÍO</span><span style={{ color: 'var(--brass)' }}>{recogerEnTienda ? 'RECOGER EN TIENDA' : 'A COORDINAR'}</span></div>
            </div>

            <p className="f-display brass" style={{ fontSize: '28px', textAlign: 'right', marginTop: '16px' }}>Total: Q {cart.total}</p>
            {errorMsg && <p className="eyebrow" style={{ color: 'var(--velvet)', fontSize: '10px', marginTop: '8px' }}>{errorMsg}</p>}

            <div style={{ display: 'flex', gap: '10px', marginTop: '20px' }}>
              <button className="btn btn-outline" style={{ flex: 1, height: '44px' }} onClick={() => setShowConfirm(false)}>CANCELAR</button>
              <button className="btn btn-primary" style={{ flex: 1, height: '44px' }} onClick={checkout} disabled={loading}>{loading ? 'PROCESANDO…' : 'CONFIRMAR →'}</button>
            </div>
          </div>
        </div>
      )}

      {confirmacion && (
        <div className="confirm-overlay">
          <div className="confirm-card hairline">
            <p className="eyebrow velvet" style={{ fontSize: '10px' }}>● PEDIDO CONFIRMADO</p>
            <h2 className="f-display" style={{ fontSize: '36px', marginTop: '12px' }}>¡Listo, <em className="accent">{auth.user?.nombre?.split(' ')[0]}!</em></h2>
            <p className="f-serif" style={{ fontSize: '18px', color: 'var(--mute)', marginTop: '8px' }}>Tu pedido #{confirmacion.id_compra} ha sido registrado.</p>
            <div className="confirm-items">
              {confirmacion.items.map(item => (
                <div key={item.id_producto} className="eyebrow confirm-item">
                  {item.nombre_producto} × {item.cantidad} — Q {Number(item.subtotal).toLocaleString('es-GT')}
                </div>
              ))}
            </div>
            <p className="f-display brass" style={{ fontSize: '24px', marginTop: '16px' }}>Total: Q {confirmacion.total}</p>
            <div style={{ display: 'flex', gap: '12px', marginTop: '24px' }}>
              <Link to="/perfil" className="btn btn-outline" style={{ height: '44px', flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>VER MIS PEDIDOS</Link>
              <Link to="/" className="btn btn-primary" style={{ height: '44px', flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>SEGUIR COMPRANDO</Link>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
